version: '3.9'
services:
  api:
    build:
      context: .
    image: order-service
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    restart: on-failure
    networks:
      - order_management_network

networks:
  order_management_network:
