version: '3.9'
services:
  api:
    build:
      context: .
    image: order-service
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env.db
    ports:
      - "5433:5433"
    networks:
      - order_management_network

volumes:
  postgres:

networks:
  order_management_network:
