apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  # Base64 encoded
  DB_PASSWORD: TGVrYW5AODAz
  OKTA_CLIENT_SECRET: RnNSTmo5dkpMMGZaZU5FWXQ2c3ZoaFVpMXctaEZrMTRyWUJxNE9rc05WZmROdV9pOVpScXVfV0VZdXc5dU9Tbg==
  EMAIL_HOST_PASSWORD: TG9ndW1vMTQh
