apiVersion: v1
kind: Service
metadata:
  name: order-management-api-service
spec:
  selector:
    app: order-management-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-management-api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-management-api-deployment
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50
